<a href="https://colab.research.google.com/github/merinrose4007/DSA-class-activity/blob/main/data_acquistion_case_study_MerinRose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import pandas as pd

#● Load the CSV file using pandas.read_csv()
#● Load the Excel file using pandas.read_excel()
#● Load the JSON file using Python’s json module
#● Parse the XML file using xml.etree.ElementTree

data1 = pd.read_csv('/content/population.csv')
data2 = pd.read_excel('/content/gdp.xlsx')
data3 = pd.read_xml('/content/literacy_rate.xml')
data4 = pd.read_json('/content/internet_users.json')

Standardize country names across all datasets

In [18]:
data1['country'].unique()

array(['United States', 'China', 'India', 'Japan', 'Germany', 'Russia',
       'Brazil', 'United Kingdom', 'France', 'Italy', 'Canada',
       'Australia', 'South Korea', 'Spain', 'Mexico', 'Indonesia',
       'Turkey', 'Saudi Arabia', 'Argentina', 'South Africa'],
      dtype=object)

In [23]:
data2

           Country             GDP
0    United States  10450436373455
1            China   5086547998939
2            India  14540718118693
3            Japan  12473835857216
4          Germany   2038442396490
5           Russia  10987125474745
6           Brazil   8793052816619
7   United Kingdom  11799848684255
8           France   7758669752269
9            Italy  12907234326850
10          Canada   8158351525190
11       Australia   5444267975247
12     South Korea   6562909541266
13           Spain  15275513099842
14          Mexico   2775281278756
15       Indonesia  12404144955318
16          Turkey   2581127745611
17    Saudi Arabia   8855399647233
18       Argentina   8767336567320
19    South Africa   3328747361982

In [25]:
data2['Country'].unique()

array(['United States', 'China', 'India', 'Japan', 'Germany', 'Russia',
       'Brazil', 'United Kingdom', 'France', 'Italy', 'Canada',
       'Australia', 'South Korea', 'Spain', 'Mexico', 'Indonesia',
       'Turkey', 'Saudi Arabia', 'Argentina', 'South Africa'],
      dtype=object)

In [28]:
data3

              name  literacy_rate
0    United States           72.7
1            China           82.2
2            India           80.3
3            Japan           97.5
4          Germany           92.9
5           Russia           89.1
6           Brazil           81.0
7   United Kingdom           82.9
8           France           97.6
9            Italy           83.7
10          Canada           70.8
11       Australia           71.6
12     South Korea           66.4
13           Spain           60.6
14          Mexico           76.5
15       Indonesia           75.4
16          Turkey           71.4
17    Saudi Arabia           60.5
18       Argentina           67.8
19    South Africa           87.7

In [29]:
data3['name'].unique()

array(['United States', 'China', 'India', 'Japan', 'Germany', 'Russia',
       'Brazil', 'United Kingdom', 'France', 'Italy', 'Canada',
       'Australia', 'South Korea', 'Spain', 'Mexico', 'Indonesia',
       'Turkey', 'Saudi Arabia', 'Argentina', 'South Africa'],
      dtype=object)

In [30]:
data4

           country  internet_users
0    United States       745595490
1            China       685275917
2            India       606850704
3            Japan      1112451555
4          Germany       246827121
5           Russia       162156967
6           Brazil        24027075
7   United Kingdom       266047041
8           France       216417853
9            Italy        87191493
10          Canada       894102645
11       Australia       201619113
12     South Korea       291770691
13           Spain       794943861
14          Mexico       135489564
15       Indonesia         4584702
16          Turkey       128924625
17    Saudi Arabia       108944665
18       Argentina       421477197
19    South Africa       739194223

In [32]:
data4['country'].unique()

array(['United States', 'China', 'India', 'Japan', 'Germany', 'Russia',
       'Brazil', 'United Kingdom', 'France', 'Italy', 'Canada',
       'Australia', 'South Korea', 'Spain', 'Mexico', 'Indonesia',
       'Turkey', 'Saudi Arabia', 'Argentina', 'South Africa'],
      dtype=object)

Since all the countries are represented in gthe same way across all the datset there is no need to standardise

In [33]:
data2 = data2.rename(columns={"Country": "country"})

In [34]:
data3 = data3.rename(columns={"name": "country"})

Convert numeric columns to appropriate types

In [37]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   country     20 non-null     object
 1   population  20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [38]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  20 non-null     object
 1   GDP      20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

In [39]:
data3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   country        20 non-null     object
 1   literacy_rate  20 non-null     float64
dtypes: float64(1), object(1)
memory usage: 452.0+ bytes

In [40]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   country         20 non-null     object
 1   internet_users  20 non-null     int64
dtypes: int64(1), object(1)
memory usage: 452.0+ bytes

Numerical columns are all already in numerical data type

Handle missing or erroneous data

In [43]:
data1.isna().sum()

country       0
population    0
dtype: int64

In [44]:
data1.isna().sum()

country       0
population    0
dtype: int64

In [45]:
data2.isna().sum()

country    0
GDP        0
dtype: int64

In [46]:
data3.isna().sum()

country          0
literacy_rate    0
dtype: int64

In [47]:
data4.isna().sum()

country           0
internet_users    0
dtype: int64

No null values

Create new columns such as internet penetration rate (internet users / population × 100)

In [48]:
data4['internet_penetration_rate'] = data4['internet_users']*100/data1['population']

In [49]:
data4

           country  internet_users  internet_penetration_rate
0    United States       745595490                  58.311493
1            China       685275917                  86.432366
2            India       606850704                  60.599844
3            Japan      1112451555                  92.222917
4          Germany       246827121                  57.571026
5           Russia       162156967                  38.519997
6           Brazil        24027075                   3.559066
7   United Kingdom       266047041                  39.414880
8           France       216417853                  49.821208
9            Italy        87191493                  34.264333
10          Canada       894102645                  62.165251
11       Australia       201619113                  45.897039
12     South Korea       291770691                  47.165661
13           Spain       794943861                  88.458317
14          Mexico       135489564                  20.746845
15       Indonesia         4584702                   4.908162
16          Turkey       128924625                  52.135863
17    Saudi Arabia       108944665                  11.366429
18       Argentina       421477197                  29.415710
19    South Africa       739194223                  80.610976

Merge the datasets based on the country name

In [50]:
data = data1.merge(data2, on="country") \
            .merge(data3, on="country") \
            .merge(data4, on="country")

print(data)

           country  population             GDP  literacy_rate  internet_users  \
0    United States  1278642419  10450436373455           72.7       745595490
1            China   792846414   5086547998939           82.2       685275917
2            India  1001406378  14540718118693           80.3       606850704
3            Japan  1206263687  12473835857216           97.5      1112451555
4          Germany   428734972   2038442396490           92.9       246827121
5           Russia   420968276  10987125474745           89.1       162156967
6           Brazil   675094950   8793052816619           81.0        24027075
7   United Kingdom   674991378  11799848684255           82.9       266047041
8           France   434389014   7758669752269           97.6       216417853
9            Italy   254467210  12907234326850           83.7        87191493
10          Canada  1438267572   8158351525190           70.8       894102645
11       Australia   439285667   5444267975247           71.6       201619113
12     South Korea   618608295   6562909541266           66.4       291770691
13           Spain   898664919  15275513099842           60.6       794943861
14          Mexico   653061058   2775281278756           76.5       135489564
15       Indonesia    93409749  12404144955318           75.4         4584702
16          Turkey   247285876   2581127745611           71.4       128924625
17    Saudi Arabia   958477463   8855399647233           60.5       108944665
18       Argentina  1432830251   8767336567320           67.8       421477197
19    South Africa   916989541   3328747361982           87.7       739194223

    internet_penetration_rate
0                   58.311493
1                   86.432366
2                   60.599844
3                   92.222917
4                   57.571026
5                   38.519997
6                    3.559066
7                   39.414880
8                   49.821208
9                   34.264333
10                  62.165251
11                  45.897039
12                  47.165661
13                  88.458317
14                  20.746845
15                   4.908162
16                  52.135863
17                  11.366429
18                  29.415710
19                  80.610976

Handle unmatched or missing records

In [63]:
print(data.info())  #no null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   country                    20 non-null     object
 1   population                 20 non-null     int64
 2   GDP                        20 non-null     int64
 3   literacy_rate              20 non-null     float64
 4   internet_users             20 non-null     int64
 5   internet_penetration_rate  20 non-null     float64
dtypes: float64(2), int64(3), object(1)
memory usage: 1.1+ KB
None

Validate the data for consistency and completeness

In [51]:
print(data.duplicated().sum())

0

In [64]:
print(data.describe())

         population           GDP  literacy_rate  internet_users  \
count  2.000000e+01  2.000000e+01      20.000000    2.000000e+01
mean   7.432343e+08  8.549450e+12      78.430000    3.936946e+08
std    3.947080e+08  4.076091e+12      11.025144    3.302706e+08
min    9.340975e+07  2.038442e+12      60.500000    4.584702e+06
25%    4.329755e+08  5.354838e+12      71.250000    1.338483e+08
50%    6.750432e+08  8.780195e+12      78.400000    2.564371e+08
75%    9.692097e+08  1.195092e+13      84.700000    6.987555e+08
max    1.438268e+09  1.527551e+13      97.600000    1.112452e+09

       internet_penetration_rate
count                  20.000000
mean                   48.179369
std                    26.486917
min                     3.559066
25%                    33.052178
50%                    48.493434
75%                    60.991196
max                    92.222917

In [53]:
print(data.dtypes)

country                       object
population                     int64
GDP                            int64
literacy_rate                float64
internet_users                 int64
internet_penetration_rate    float64
dtype: object

In [54]:
data[(data["literacy_rate"] < 0) | (data["literacy_rate"] > 100)]

Empty DataFrame
Columns: [country, population, GDP, literacy_rate, internet_users, internet_penetration_rate]
Index: []

In [55]:
data[(data["internet_penetration_rate"] < 0) | (data["internet_penetration_rate"] > 100)]

Empty DataFrame
Columns: [country, population, GDP, literacy_rate, internet_users, internet_penetration_rate]
Index: []

In [56]:
data["country"].duplicated().sum()

np.int64(0)

Find countries with highest internet penetration rates

In [58]:
data_max=data[data['internet_penetration_rate']==data['internet_penetration_rate'].max()]

In [59]:
data_max['country']

3    Japan
Name: country, dtype: object

Calculate average literacy rate across countries

In [60]:
data['literacy_rate'].mean()

np.float64(78.43)

 Investigate relationships between GDP, population, literacy, and internet usage

In [61]:
correlation = data[["GDP", "population", "literacy_rate", "internet_users"]].corr()

print(correlation)

                     GDP  population  literacy_rate  internet_users
GDP             1.000000    0.183118      -0.081700        0.212559
population      0.183118    1.000000      -0.229585        0.749573
literacy_rate  -0.081700   -0.229585       1.000000        0.074808
internet_users  0.212559    0.749573       0.074808        1.000000

Load into SQLite:

In [66]:
#● Create an SQLite database
import sqlite3
conn = sqlite3.connect("country.db")
cursor = conn.cursor()

In [67]:
#● Load the final merged dataset into a database table
data.to_sql("final_dataset", conn, if_exists="replace", index=False)

20

In [72]:
result = pd.read_sql("SELECT * FROM final_dataset", conn)
print(result.head())

         country  population             GDP  literacy_rate  internet_users  \
0  United States  1278642419  10450436373455           72.7       745595490
1          China   792846414   5086547998939           82.2       685275917
2          India  1001406378  14540718118693           80.3       606850704
3          Japan  1206263687  12473835857216           97.5      1112451555
4        Germany   428734972   2038442396490           92.9       246827121

   internet_penetration_rate
0                  58.311493
1                  86.432366
2                  60.599844
3                  92.222917
4                  57.571026

In [74]:
#Countries with highest internet penetration
cursor.execute("SELECT country FROM final_dataset order by internet_penetration_rate desc limit 1")
print(cursor.fetchall())

[('Japan',)]

In [76]:
# Average literacy rate
cursor.execute("select avg(literacy_rate) from final_dataset")
print(cursor.fetchall())

[(78.43,)]

In [87]:
# Correlation between literacy rate and internet penetration

cursor.execute("SELECT (COUNT(*) * SUM(literacy_rate * internet_penetration_rate) - SUM(literacy_rate) * SUM(internet_penetration_rate))/ SQRT((COUNT(*) * SUM(literacy_rate * literacy_rate) - POWER(SUM(literacy_rate), 2)) *(COUNT(*) * SUM(internet_penetration_rate * internet_penetration_rate) - POWER(SUM(internet_penetration_rate), 2))) AS correlation FROM final_dataset;")
print(cursor.fetchall())

[(0.2353300920270708,)]

In [89]:
#GDP per capita analysis
cursor.execute("select country, GDP/population as gdp_per_capita from final_dataset ORDER BY gdp_per_capita DESC")
print(cursor.fetchall())

[('Indonesia', 132792), ('Italy', 50722), ('Russia', 26099), ('France', 17861), ('United Kingdom', 17481), ('Spain', 16998), ('India', 14520), ('Brazil', 13024), ('Australia', 12393), ('South Korea', 10609), ('Turkey', 10437), ('Japan', 10340), ('Saudi Arabia', 9239), ('United States', 8173), ('China', 6415), ('Argentina', 6118), ('Canada', 5672), ('Germany', 4754), ('Mexico', 4249), ('South Africa', 3630)]

In [90]:
# Which countries have a GDP per capita above $10,000?
cursor.execute("select country, GDP/population as gdp_per_capita from final_dataset where gdp_per_capita>10000")
print(cursor.fetchall())

[('India', 14520), ('Japan', 10340), ('Russia', 26099), ('Brazil', 13024), ('United Kingdom', 17481), ('France', 17861), ('Italy', 50722), ('Australia', 12393), ('South Korea', 10609), ('Spain', 16998), ('Indonesia', 132792), ('Turkey', 10437)]

In [92]:
# What is the total population covered in the dataset?
cursor.execute("select sum(population) from final_dataset")
print(cursor.fetchall())

[(14864685089,)]

In [115]:
#Which countries have the lowest literacy rates, and how does that impact internet access?

cursor.execute("select country, literacy_rate, internet_penetration_rate from final_dataset order by literacy_rate asc limit 1")
print(cursor.fetchall())

# Saudi Arabia has the lowest literacy rate hence their internet usage is also low

[('Saudi Arabia', 60.5, 11.36642948901554)]

In [116]:
#What are the top 5 wealthiest countries by total GDP, and how does that compare with population size?

cursor.execute("select country, GDP, population, GDP/population as gdp_per_capita from final_dataset order by GDP desc limit 5")
print(cursor.fetchall())

# For India and Japan Huge populations dilute per-person wealth.
# For Italy and Spain Smaller populations mean that even moderately high GDP translates into higher wealth per person.

[('Spain', 15275513099842, 898664919, 16998), ('India', 14540718118693, 1001406378, 14520), ('Italy', 12907234326850, 254467210, 50722), ('Japan', 12473835857216, 1206263687, 10340), ('Indonesia', 12404144955318, 93409749, 132792)]

In [114]:
# Find countries where internet users exceed 70% of the population
cursor.execute("""SELECT
    country,
    (internet_users * 100.0 / population) AS percent
FROM final_dataset
WHERE percent > 70""")
print(cursor.fetchall())

[('China', 86.4323663321759), ('Japan', 92.22291667974251), ('Spain', 88.45831679783197), ('South Africa', 80.61097645605535)]

In [111]:
# What is the average GDP per capita for countries with internet penetration above 50%?

cursor.execute("select avg(GDP/population) as gdp_per_capita from final_dataset where internet_penetration_rate>50")
print(cursor.fetchall())

[(8993.222222222223,)]

In [112]:
# How many countries have a literacy rate above 90%, and what is their average internet penetration rate?
cursor.execute('select count(*), avg(internet_penetration_rate) from final_dataset where literacy_rate>90')
print(cursor.fetchall())

[(3, 66.53838337489236)]